server:
  port: 8761

spring:
  application:
    name: registerCloudServer
#  cloud:
#    config:
#      uri: http://localhost:8761/
#      label: master



eureka:
  environment: test
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-withEureka: true
    fetch-registry: false
    prefer-same-zone-eureka: true
    region: SH
    availability-zones:
          SH: zone-test,zone-dev
    service-url:
          zone-test: http://localhost:8761/eureka/
          zone-dev: http://localhost:8762/eureka/


