server:
  port: 8883
  servlet:
    context-path: /

spring:
  application:
    name: appclient
  cloud:
    config:
      uri: http://localhost:8761/
      label: master


eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${server.port}
        nonSecurePort: 8883
        status-page-url-path: /actuator/info
        health-check-url-path: /actuator/health
        metadata-map:
              zone: zone-test
    client:
       register-with-eureka: true
       fetch-registry: true
       prefer-same-zone-eureka: true
       #地区
       region: SH
       availability-zones:
            SH: zone-test,zone-dev
       service-url:
            zone-dev: http://localhost:8762/eureka/
            zone-test: http://localhost:8761/eureka/

zone-name: zone-test


logging:
  level:
    org:
      springframework:
        security: DEBUG


spring.cloud.vault:
    config.lifecycle.enabled: true
    fail-fast: true