server:
  port: 10002

spring:
  application:
    name: boot-admin-client
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:10001
#  cloud:
#    config:
#      uri: http://localhost:8761/
#      label: master


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
